spring.config.import=optional:file:.env[.properties]
spring.application.name=fsad-project
server.port=${PORT:3306}

# Railway MySQL connection
spring.datasource.url=jdbc:mysql://root:KbTJpnHYfWKCoPHMfkKvzfVRqakqlHsS@switchback.proxy.rlwy.net:56481/railway
spring.datasource.username=root
spring.datasource.password=KbTJpnHYfWKCoPHMfkKvzfVRqakqlHsS
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}
app.jwt.secret=f8a9c1e6b2d3475fa91c8b2e4d6f7a9c3e1b5d8f0a2c4e6b8d1f3a5c7e9b2d4
